version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 8085:80
    volumes:
      - ./srv:/srv
      - ./.filebrowser.json:/.filebrowser.json
      - ./filebrowser.db:/database.db
networks:
  default:
    external:
      name: fb-network
